### ISSUE TITLE
Not compile new  StreamMP3FromHTTP.ino

### ISSUE THREAD

**Issue by renat2985** [earlephilhower/ESP8266Audio#10]
Tell me please what is the problem?

![2017 11 20-22 07 07](https://user-images.githubusercontent.com/1230815/33039003-2fc0dc78-ce3f-11e7-9944-3fc51957e0b8.png)

**Comment by earlephilhower** [comment]
Ack, I did an amended commit but didn't push it to GitHub this AM before work.  Please pull the repo once again and the example will work.

The problem is "mp3->begin(buff, out);" is what it should be, not file,buff...

**Comment by renat2985** [comment]
Thanks!
