### ISSUE TITLE
Update or delete Platformio library entry

### ISSUE THREAD

**Issue by Oliv4945** [earlephilhower/ESP8266Audio#103]
Hi,

First, thank your for your library: it works like a charm when I2S clock & data pin are not inverted on my side :)

[Platformio ](https://platformio.org/lib/show/1964/ESP8266Audio/examples) library is a outdated, which can lead people to think that the library is not working because you corrected lot of bugs since November, 2017.
It would avoid confusion if you update or delete it :)

**Comment by earlephilhower** [comment]
Howdy,

I didn't create that Platform.IO library, so I'll have to figure out who did and how it would be updated.  Have you any libraries there?  Would you be able to give any pointers?

From a quick glance I need to bump the library version in the repo, PIO doesn't seem to grab updates to an existing rev.

**Comment by Oliv4945** [comment]
I never published any library but I will check it for you :)

**Comment by earlephilhower** [comment]
Thanks, @Oliv4945 , but by bumping the rev number I was able to get the latest version "1.1" up on Platform.IO.

Looks like we're good now.  Thanks again for letting me in on this, I'd never have known otherwise.

**Comment by Oliv4945** [comment]
Yes I so that yesterday, thank you !
