### ISSUE TITLE
Repeated playback issue

### ISSUE THREAD

**Issue by 2SangH** [earlephilhower/ESP8266Audio#108]
First, thank you very much for your wonderful library. I'm going to use your example to implement an example of playing sound if the switch is pressed. The first start plays very well. However, if the button is pressed for the second replay, the overflow (?) occurs and is reset. I tried the while door and moved it to the location of mp3 - > begin, but it was hard to find a solution for days. Can you help me?

hardware : nodemcu1.0  V2

code: 

#include <Arduino.h>
#ifdef ESP32
  #include <WiFi.h>
  #include "SPIFFS.h"
#else
  #include <ESP8266WiFi.h>
#endif
#include "AudioFileSourceSPIFFS.h"
#include "AudioFileSourceID3.h"
#include "AudioGeneratorMP3.h"
#include "AudioOutputI2SNoDAC.h"

// To run, set your ESP8266 build to 160MHz, and include a SPIFFS of 512KB or greater.
// Use the "Tools->ESP8266/ESP32 Sketch Data Upload" menu to write the MP3 to SPIFFS
// Then upload the sketch normally.  

// pno_cs from https://ccrma.stanford.edu/~jos/pasp/Sound_Examples.html

AudioGeneratorMP3 *mp3;
AudioFileSourceSPIFFS *file;
AudioOutputI2SNoDAC *out;
AudioFileSourceID3 *id3;

// Called when a metadata event occurs (i.e. an ID3 tag, an ICY block, etc.
void MDCallback(void *cbData, const char *type, bool isUnicode, const char *string)
{
  (void)cbData;
  Serial.printf("ID3 callback for: %s = '", type);

  if (isUnicode) {
    string += 2;
  }
  
  while (*string) {
    char a = *(string++);
    if (isUnicode) {
      string++;
    }
    Serial.printf("%c", a);
  }
  Serial.printf("'\n");
  Serial.flush();
}

#define sw D0      
int state = LOW;      
int reading;        int previous = LOW;  
 
long time1 = 0;        
long debounce = 100;  

void setup()
{
  WiFi.mode(WIFI_OFF); 
  Serial.begin(115200);
  delay(1000);
  SPIFFS.begin();
  Serial.printf("Sample MP3 playback begins...\n");
  file = new AudioFileSourceSPIFFS("/pno-cs.mp3");
  id3 = new AudioFileSourceID3(file);
  id3->RegisterMetadataCB(MDCallback, (void*)"ID3TAG");
  out = new AudioOutputI2SNoDAC();
  mp3 = new AudioGeneratorMP3();
  mp3->begin(id3, out);
  
  pinMode(sw, INPUT);

}
int cnt1=0;
int cnt2=0;
void loop()
{
  /*
  if (mp3->isRunning()) {
    if (!mp3->loop()) mp3->stop();
  } else {
    Serial.printf("MP3 done\n");
    delay(1000);*/

  reading = digitalRead(sw);  
 

  if (reading == HIGH && previous == LOW && millis() - time1 > debounce) {
    if (state == HIGH)   
      state = LOW;
    else                
      state = HIGH;
 
    time1 = millis();
  }
  previous = reading;

////////////////////  toggle  ////////////////////

  Serial.print("State : ");
  Serial.println(state);

    if(state == HIGH){
      
      Serial.println("HIGH");
      mp3->begin(id3, out);
      if(mp3->isRunning()){

        }
      
      if(!mp3->loop()) {
        Serial.println("stop");
        mp3->stop();
        state = LOW;
        
        }
      }
    
  }

**Comment by earlephilhower** [comment]
My demos are much worse examples of coding than my libraries, I'm afraid to admit.  The problem is that you need to `delete mp3;` (and all the other objects) before creating a new one, as each one takes 20KB++.  For the demo, it just idles after the playback so no problem not deleting since it never does anything.  For your code, you'll need to clean up memory before starting a new one...
