### ISSUE TITLE
MP3 class: Filter data that doesn't start with 0xFFFx.

### ISSUE THREAD

**Issue by armSeb** [earlephilhower/ESP8266Audio#11]
This issue is related to issue #7. Sometimes the stream have some tags (LAME), as described here: http://gabriel.mp3-tech.org/mp3infotag.html

Is seems to cause problems with the ICY parser class.

**Comment by earlephilhower** [comment]
This may have been a false alarm due to ICY corruption.  I'll leave it sit for a while and if it doesn't pop up I'll just close it.

**Comment by earlephilhower** [comment]
I don't think I've seen this since I fixed a couple bugs in the ICY decoder.  If you've not seen it, either, let's close this for now.

**Comment by earlephilhower** [comment]
Closing, seems to have been a false alarm.
