### ISSUE TITLE
Need more RAM... Codec in SPIRAM ?

### ISSUE THREAD

**Issue by Mael19** [earlephilhower/ESP8266Audio#112]
Hello, first thank you for this amazing library ! I have my program working well with the  	StreamMP3FromHTTP_SPIRAM example. But I need to add some functions to the program and I am running out of RAM quite fast ! As we're already using SPIRAM to store the buffer, would it be possible to use the RAM to store the codec as well ? This would let us more RAM for the rest of the program. Sorry if my request is impossible, I'm quite new to arduino programming... I'll still try to figure it out by myself but this is quite complicated for me !

**Comment by earlephilhower** [comment]
Sorry, but not really.  The program itself is already in flash, not RAM, and the rest of RAM is used for the MP3 decode and other bits which can't run outside the chip.  It's just tight, unfortunately.  Use GIT head for the Arduino core, if you're not, and you can get an add'l 4KB of RAM free, though.
