### ISSUE TITLE
Using esp32 with SpiRAM

### ISSUE THREAD

**Issue by Mael19** [earlephilhower/ESP8266Audio#121]
Hello, I finally managed to make my esp32 work. I'd like to use it with the SpiRAM as well, is it possible ? Has someône done it ?

**Comment by h3ndrik** [comment]
Have a look at examples/StreamMP3FromHTTP_SPIRAM in this project.

**Comment by TheNitek** [comment]
You can use it like this:
  uint32_t spiBufferSize = 4*1024*1024;
  byte *spiBuffer = (byte*)ps_malloc(spiBufferSize);
  buff = new AudioFileSourceBuffer(file, spiBuffer, spiBufferSize);

(you need to enable PSRAM in Arduino IDE => Tools)
