### ISSUE TITLE
Compile problem missing ESP8266Spiram.h

### ISSUE THREAD

**Issue by jeffrchristensen** [earlephilhower/ESP8266Audio#126]
Hi,

Sorry I am sure I am doing something stupid with my environment. I am using Platformio + Atom.

I am using the latest espressif8266
```
[env:huzzah]
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
board = huzzah
framework = arduino
```

I get the following error:

```
Compiling .pioenvs/huzzah/libf39/ESP8266Audio_ID1964/AudioGeneratorMP3.cpp.o
In file included from /home/jeff/.platformio/lib/ESP8266Audio_ID1964/src/AudioFileSourceSPIRAMBuffer.cpp:23:0:

/home/jeff/.platformio/lib/ESP8266Audio_ID1964/src/AudioFileSourceSPIRAMBuffer.h:27:76: fatal error: ESP8266Spiram.h: No such file or directory
 
***********************************************************************
* Looking for ESP8266Spiram.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESP8266Spiram.h"
* Web  > https://platformio.org/lib/search?query=header:ESP8266Spiram.h
*
***********************************************************************
 
#include <ESP8266Spiram.h> // https://github.com/Gianbacchio/ESP8266_Spiram
^
compilation terminated.
*** [.pioenvs/huzzah/libf39/ESP8266Audio_ID1964/AudioFileSourceSPIRAMBuffer.cpp.o] Error 1
```

Even if I manually install the ESP8266Spiram library explicitly I still get the same error.

**Comment by darookee** [comment]
I had the same problem with platform.io. Add this to your `platformio.ini` env:
```
lib_deps =
    ESP8266Spiram
```

**Comment by jeffrchristensen** [comment]
That works.

Thanks.

btw - What is the difference between doing that and manually installing ESP8266Spiram?

**Comment by earlephilhower** [comment]
Is there a setting in library file for platform.Io that I can add to the repo to get this included automatically?

**Comment by moose4lord** [comment]
Or better yet, can you remove the dependency on the spiram lib? Seems silly to require it if you don't have a spiram module.

**Comment by earlephilhower** [comment]
It actually doesn't need the module unless you use the `AudioFileSourceSPIRAMBuffer`.  So, if you're not running it then this is a bug in PlatformIO's dependency/build process.  It's not an issue with the native Arduino processes which are slower but seem to be less prone to spurious dependencies.

If you can find a setting in the library.properties/.json, I'm happy to add that in.

**Comment by itsjustvenky** [comment]
@earlephilhower Here the info. on adding library dependencies.

https://docs.platformio.org/en/latest/librarymanager/config.html#dependencies

**Comment by moose4lord** [comment]
Hmmm...I'm using the vanilla Arduino IDE v1.8.6 on a Mac and if I try to compile the PlayWAVFromPROGMEM example sketch without the ESP8266Spiram library installed, I get this error:
```
In file included from /Users/klord/Documents/Arduino/libraries/ESP8266Audio/src/AudioFileSourceSPIRAMBuffer.cpp:23:0:
/Users/klord/Documents/Arduino/libraries/ESP8266Audio/src/AudioFileSourceSPIRAMBuffer.h:27:76: fatal error: ESP8266Spiram.h: No such file or directory
 #include <ESP8266Spiram.h> // https://github.com/Gianbacchio/ESP8266_Spiram
                                                                            ^
compilation terminated.
exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).
```

The example sketch doesn't seem to include the Spiram functions, yet the IDE tries to compile the AudioFileSourceSPIRAMBuffer.cpp file anyway. Have I got something misconfigured?

**Comment by earlephilhower** [comment]
Huh, looks like it does bring it in under Arduino, @moose4lord!  Weird.  I'll add in a dependency to the JSON.

@jeffrchristensen , you've got something very weird going on with PlatformIO.  That missing `SPI.h` is part of the core libraries distributed w/Arduino.  If it can't find it, then PIO is just plain broken and you'll want to submit a bug there to see what's up.  Maybe a partial download/install of the core libs?

**Comment by jeffrchristensen** [comment]
Got it.

**Comment by earlephilhower** [comment]
I've just pushed an updated library.* with dependencies explicitly listed for ESP8266Spiram (and SPI, maybe that will help you out @jeffrchristensen).  I think PIO does nightly pulls to update their libs index, so you can try again in a day.

**Comment by jeffrchristensen** [comment]
Hey Earle,

I will take this to platformio but I also wanted to check with you. I was still hitting problems finding SD.h from your code. This is super odd because it is there in the framework source.

I did notice that in the actual compile statement it doesn't have the explicit include path for SD.h. Any ways I'll get to that.

To properly diagnose this I did a full reinstall of Platformio. I removed ".platformio" just to be sure on reinstall.

There still seems to be something odd with the dependencies.

My ini file:
```
[env:huzzah]
lib_deps = ESP8266Spiram
platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
framework = arduino
build_flags = -Wl,-Teagle.flash.4m1m.ld
board = huzzah
```

Installing your library from the package manager:

```
jeff@jc01 test]$ pio lib install ESP8266Audio
Library Storage: /home/jeff/Documents/PlatformIO/Projects/test/.piolibdeps
Looking for ESP8266Audio library in registry
Found: https://platformio.org/lib/show/1964/ESP8266Audio
LibraryManager: Installing id=1964

Downloading...
Unpacking...
ESP8266Audio @ 1.1.3 has been successfully installed!
Installing dependencies
LibraryManager: Installing id=5417 @ 1.0
ESP8266Spiram @ 1.0 is already installed
Looking for SPI library in registry
Warning! Library `{'version': u'1.0', 'name': u'SPI'}` has not been found in PlatformIO Registry.
You can ignore this message, if `{'version': u'1.0', 'name': u'SPI'}` is a built-in library (included in framework, SDK). E.g., SPI, Wire, etc.
[jeff@jc01 test]$
```

**Comment by jeffrchristensen** [comment]
So this is my attempt to compile where it can't compile your "AudioFileSourceCD.cpp" file:

```
[jeff@jc01 test]$ pio run -v
Processing huzzah (platform: https://github.com/platformio/platform-espressif8266.git#feature/stage; lib_deps: ESP8266Spiram; build_flags: -Wl,-Teagle.flash.4m1m.
ld; board: huzzah; framework: arduino)
------------------------------------------------------------------------------------------------------------------------------------------------------------------
Library Storage: /home/jeff/Documents/PlatformIO/Projects/test/.piolibdeps
LibraryManager: Installing id=5417
ESP8266Spiram @ 1.0 is already installed
PLATFORM: Espressif 8266 (Stage) > Adafruit HUZZAH ESP8266
SYSTEM: ESP8266 80MHz 80KB RAM (4MB Flash)
Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF MODES: FINDER(chain) COMPATIBILITY(soft)
Collected 30 compatible libraries

Scanning dependencies...
Dependency Graph
|-- <ESP8266Spiram> 1.0 (/home/jeff/Documents/PlatformIO/Projects/test/.piolibdeps/ESP8266Spiram_ID5417)
|   |-- <SPI> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/SPI)
|-- <ESP8266WiFi> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi)
|-- <ESP8266Audio> 1.1.3 (/home/jeff/Documents/PlatformIO/Projects/test/.piolibdeps/ESP8266Audio_ID1964)
|   |-- <ESP8266Spiram> 1.0 (/home/jeff/Documents/PlatformIO/Projects/test/.piolibdeps/ESP8266Spiram_ID5417)
|   |   |-- <SPI> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/SPI)
|   |-- <SPI> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/SPI)
|   |-- <ESP8266HTTPClient> 1.1 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient)
|   |   |-- <ESP8266WiFi> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi)
|-- <ESP8266HTTPClient> 1.1 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient)
|   |-- <ESP8266WiFi> 1.0 (/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi)
xtensa-lx106-elf-g++ -o .pioenvs/huzzah/lib9bd/ESP8266Audio_ID1964/AudioFileSourceSD.cpp.o -c -fno-rtti -fno-exceptions -std=c++11 -Os -mlongcalls -mtext-section-
literals -falign-functions=4 -U__STRICT_ANSI__ -ffunction-sections -fdata-sections -Wall -DPLATFORMIO=30601 -DESP8266 -DARDUINO_ARCH_ESP8266 -DARDUINO_ESP8266_ESP
12 -DF_CPU=80000000L -D__ets__ -DICACHE_FLASH -DARDUINO=10805 -DARDUINO_BOARD=\"PLATFORMIO_HUZZAH\" -DLWIP_OPEN_SRC -DVTABLES_IN_FLASH -I/home/jeff/.platformio/pa
ckages/framework-arduinoespressif8266/tools/sdk/include -I/home/jeff/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include -
I/home/jeff/.platformio/packages/framework-arduinoespressif8266/cores/esp8266 -I/home/jeff/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lwip/incl
ude -I/home/jeff/.platformio/packages/framework-arduinoespressif8266/variants/adafruit -I/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/
SPI -I.piolibdeps/ESP8266Spiram_ID5417/src -I/home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/ESP8266WiFi/src -I/home/jeff/.platformio/pac
kages/framework-arduinoespressif8266/libraries/ESP8266HTTPClient/src -I.piolibdeps/ESP8266Audio_ID1964/src .piolibdeps/ESP8266Audio_ID1964/src/AudioFileSourceSD.c
pp
In file included from .piolibdeps/ESP8266Audio_ID1964/src/AudioFileSourceSD.cpp:21:0:
.piolibdeps/ESP8266Audio_ID1964/src/AudioFileSourceSD.h:25:16: fatal error: SD.h: No such file or directory
```

**Comment by xfdr0805** [comment]
> If you look at the include statements in the actual command line it doesn't include:
> 
> ```
> /home/jeff/.platformio/packages/framework-arduinoespressif8266/libraries/SD/src
> ```
> which is where SD.h is located.
我也遇到了这个问题，SD.h文件确实存在，但编译时说找不这个文件

**Comment by scottw-finao** [comment]
I'm getting the same error and double checked the CMakeListsPrivate.txt and it does include:

`include_directories("$ENV{HOME}/.platformio/packages/framework-arduinoespressif8266/libraries/SD/src")`

**Comment by MuhammadQaisarAli** [comment]
> Hi,
> 
> Sorry I am sure I am doing something stupid with my environment. I am using Platformio + Atom.
> 
> I am using the latest espressif8266
> 
> ```
> [env:huzzah]
> platform = https://github.com/platformio/platform-espressif8266.git#feature/stage
> board = huzzah
> framework = arduino
> ```
> 
> I get the following error:
> 
> ```
> Compiling .pioenvs/huzzah/libf39/ESP8266Audio_ID1964/AudioGeneratorMP3.cpp.o
> In file included from /home/jeff/.platformio/lib/ESP8266Audio_ID1964/src/AudioFileSourceSPIRAMBuffer.cpp:23:0:
> 
> /home/jeff/.platformio/lib/ESP8266Audio_ID1964/src/AudioFileSourceSPIRAMBuffer.h:27:76: fatal error: ESP8266Spiram.h: No such file or directory
>  
> ***********************************************************************
> * Looking for ESP8266Spiram.h dependency? Check our library registry!
> *
> * CLI  > platformio lib search "header:ESP8266Spiram.h"
> * Web  > https://platformio.org/lib/search?query=header:ESP8266Spiram.h
> *
> ***********************************************************************
>  
> #include <ESP8266Spiram.h> // https://github.com/Gianbacchio/ESP8266_Spiram
> ^
> compilation terminated.
> *** [.pioenvs/huzzah/libf39/ESP8266Audio_ID1964/AudioFileSourceSPIRAMBuffer.cpp.o] Error 1
> ```
> 
> Even if I manually install the ESP8266Spiram library explicitly I still get the same error.

here is the solution..

include 
lib_ldf_mode = deep
in platformio.ini file.

link for reference.
https://docs.platformio.org/en/latest/librarymanager/ldf.html?utm_source=platformio&utm_medium=piohome#storage

**Comment by earlephilhower** [comment]
Closing as this lib is no longer used in the library.
