### ISSUE TITLE
Q: SPIFFS mp3 audio value  

### ISSUE THREAD

**Issue by awilkie1** [earlephilhower/ESP8266Audio#135]
Hi, Wondering if there is a value within the library that could be used as mp3 audio is playing to directly affect some LEDs? Any ideas would be great!

**Comment by earlephilhower** [comment]
If you just want amplitude, you could write a simple pass-through filter that would fit between the mp3 generator and the I2S that had some form of windowed RMS sampling.

LibMAD has a callback that I did not use that let your app see the energy in individual frequency banks (not quite FFT, but close enough).  You'd need to look at the original mad sources and example to get the exact stage where it could be called, but that's also a possibility if you really want to work at it.  You'd shim into the libmad folder itself and do your magic appropriately.
