### ISSUE TITLE
ESP8266 StreamMP3FromHTTP.ino to play some stream is good ,some is bad.

### ISSUE THREAD

**Issue by kindzhon** [earlephilhower/ESP8266Audio#141]
When I use ESP8266Audio\examples\StreamMP3FromHTTP\StreamMP3FromHTTP.ino  to play some stream like "http://ice1.somafm.com/bootliquor-128-mp3", is smooth, but when I play "http://lhttp.qingting.fm/live/1270/64k.mp3", it's so bad ,like speed up ,not smooth at all.
Can anyone tell me why ?

**Comment by MY201314MY** [comment]
I want to know what the url means?I try to open the second url in my browser,and just like a FM radio.
