### ISSUE TITLE
Possibility of simple spectrum analysing?

### ISSUE THREAD

**Issue by Gomezzzzz** [earlephilhower/ESP8266Audio#142]
ESP8266 with amazing ESP8266Audio library can be used in children electronic toys. But toys needs color leds also. :)  Is there any possibility to quickly analyse output audio spectrum to make 2-3 leds blinking in rhythm of music? (or at least possibility to detect 'music playing' and 'music stopped'?)

**Comment by earlephilhower** [comment]
You can add a filter between the AudioGenerator that quickly checks the average volume and reports that back every .1 secords or so (just look at the envelope).  You could also break in to the MP3 decoder itself.  It decodes energy in a series of frequency bands...exactly what you need for a spectrum analyzer.  That'd be more complicated, but it's also possible (see the libmad documentation on their site, there's a callback you can use).  Good luck!
