### ISSUE TITLE
Update needed for new ESP8266HTTPClient library

### ISSUE THREAD

**Issue by jgrulich** [earlephilhower/ESP8266Audio#145]
Please update the lib to work with new version of the ESP8266HTTPClient library which is now 1.2.

**Comment by itsjustvenky** [comment]
Getting compile errors. "begin()" method now takes WifiClient

**Comment by earlephilhower** [comment]
Fixed with latest push.  They were warnings, not errors, but we're not passing in a WiFiClient for streaming anyway.
