### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by Colobox** [earlephilhower/ESP8266Audio#146]
Hi Earle!
I am still playing around with Your libraries. You did a very great job!
Can you update the lib to work with HTTPS ( TLS)?

**Comment by earlephilhower** [comment]
HTTPS uses a lot of RAM (>20KB) and there's just not enough space for it and the MP3 decoder on the 8266.  On the ESP32 you could try simply replacing the HTTP streamer with a HTTPS streamer and giving it a go.

**Comment by marcelstoer** [comment]
> try simply replacing the HTTP streamer with a HTTPS streamer

Any examples for that?
