### ISSUE TITLE
SD Card use

### ISSUE THREAD

**Issue by jenshackel** [earlephilhower/ESP8266Audio#147]
Is it possible to play mp3 files stored on a connected SD card? What pins must be used for the SD card and is there any code example yet?

**Comment by darookee** [comment]
[Yes](https://github.com/earlephilhower/ESP8266Audio/blob/master/src/AudioFileSourceSD.cpp) and the code is pretty self-explanatory. Use `AudioFileSourceSD::open` with the path to the file. Remember to call `SD.begin()` first.

**Comment by jenshackel** [comment]
Thanks for your fast reply and the precious tip! I hadn’t noticed that one. Great! Now I can move on. Cheers.
