### ISSUE TITLE
#define in both MIDI and MOD files both read MOD

### ISSUE THREAD

**Issue by treii28** [earlephilhower/ESP8266Audio#148]
I'm not sure if you did this intentionally or if it is a woopsie, but I just noticed that the #define in the top of the AudioGeneratorMIDI.h appears to be identical to the one in the top of the AudioGeneratorMOD.h

```
#ifndef _AUDIOGENERATORMOD_H
#define _AUDIOGENERATORMOD_H

```

I know I have been known to do that by mistake sometimes when using one file as a basis to start another (and then forgetting to change stuff) but I've also seen some folks do that as a way to prevent two libraries that might collide from both being loaded simultaneously.  (i.e. this would prevent them both from being loaded simultaneously)

I didn't see any tickets about it so I thought I would at least point it out in case it was a cut/paste/copy issue that someone forgot to update in the MIDI version.

**Comment by earlephilhower** [comment]
Fixed in current tree.
