### ISSUE TITLE
Deactivate library messages over Serial

### ISSUE THREAD

**Issue by fabiuz7** [earlephilhower/ESP8266Audio#152]
Hi all,
I would ask if it possibile to disable the "debug" "info" messages generated by the library over the Serial port. I play many very short audio and every time mp3 file ends I get this:
```
+0 0x3ffb1d48
MP3 stop, len==0
UNINSTALL I2S
```
It is annoying because it is polluting the Serial port.
I dug a bit into the library and I found one line that generates "MP3 stop"
https://github.com/earlephilhower/ESP8266Audio/blob/2f2898c49612f1cc1351b44ffe8541def5a26b23/src/AudioGeneratorMP3.cpp#L124
It seems there is no way to deactivate these messages...

However thanks for you work!

**Comment by earlephilhower** [comment]
See the new AudioLogger class which lets these messages be thrown away, presented on an LCD, etc.
