### ISSUE TITLE
Save and jump to MP3 hh:mm:ss

### ISSUE THREAD

**Issue by DerWuckel** [earlephilhower/ESP8266Audio#156]
many thanks for this great library!

I am a beginner and hope not to ask too stupid questions.
I would like to listen my audiobooks collection on an ESP32.
is it possible to save the time hh: mm: ss and then jump back to the place of the MP3 or I have to start each time from the beginning when the power is turned off

Many thanks in advance

Wuckel

**Comment by earlephilhower** [comment]
If you save and restore the file offset, you should be able to seek() to it before calling `mp3->run()` to resume at a later point.
