### ISSUE TITLE
How to output a "realtime" sine wave?

### ISSUE THREAD

**Issue by joknjokn** [earlephilhower/ESP8266Audio#162]
Hi

I am trying to play with realtime audio. I have an ESP32 and PCM5102. I made the http-stream-example work (though it crashes after some time).

I have made a simple synthesizer on the ESP32 which works using the internal DAC.
However, how can I send the signal to the PCM5102? With the internal dac, it's just an int between 0 and 255 (or so.. 8bit dac i guess, so I could increase this) being sent with dacWrite(pinNumber,intValue) at a specific clock/interval.

How can I "convert" this "realtime int value" and send it to the PCM5102?

I also want to use it for realtime audio ADC input -> realtime ESP32 audio effects -> output to have fun with some guitar pedal effect-ish stuff.

I hope some of you can guide me in the right direction. :-)

Thanks!,
Jonas

**Comment by earlephilhower** [comment]
For an I2S setup you need to generate samples every 1/f, while an ADC doesn't care and will hold the output value you sent forever.  So you need to pick a desired sampling frequency and precalculate buffers with the sine wave of your chosed frequency, and then use DMA to transfer them.  You can't just write a value to a port, that is not fast enough nor repeatable enough.  The SDK has some examples on doing just that.

You could also look at the AudioOutputI2S.cpp and maybe even use it with your generated sampled if it makes sense. 

Good luck
-EFP3
