### ISSUE TITLE
Would it be possible to output sound using bitluni's AM radio transmitter?

### ISSUE THREAD

**Issue by bootrino** [earlephilhower/ESP8266Audio#166]
I have used this and it works fine to generate a signal that plays audio on an AM radio.

https://github.com/bitluni/ESP32AMRadioTransmitter

However the code above does not play mp3 or WAV format - it plays some sort of custom audio format.

I wondered if you think it would be possible to combine the code in this library with the AM playback techniques in https://github.com/bitluni/ESP32AMRadioTransmitter so that mp3 or WAV could be played to an AM radio?

If yes, what would be involved - what's the scale of the task do you think?

I'd be happy even to be playing mp3 files that are either loaded from spiffs or embedded in the source code somehow.

**Comment by earlephilhower** [comment]
It's not straightforward, unfortunately, but may be possible.  It looks like he is actually generating a sine wave at 800khz or so.  For AM you just need to modulate that sine wave by the decoded samples.  You'd use the same input and decode stages and need to change the AudioOutput* filter to handle the sample extension (i.e you're decoding at 44khz, but need to generate a >1MHZ output so each decoded sample will be multiplied by a bunch of sine waves.  It's not something I'd be doing, but if you get anywhere I'd be happy to link to it!.  Good luck, -EFP3
