### ISSUE TITLE
Change the audio pinout

### ISSUE THREAD

**Issue by XiaoKaiRen** [earlephilhower/ESP8266Audio#167]
Hello there
I want to replace the gpio of the sound output from io3 to io12
I am trying to put the core_esp8266_i2s.c inside
#define I2SO_DATA 12
#define I2SI_DATA 3
Make changes but no work
Is this feasible?

PS: use ESP12E

**Comment by earlephilhower** [comment]
Can't be done on the 8266, the hardware doesn't support it.  ESP32 allows changing the GPIO assignments, you can look at that chip instead.
