### ISSUE TITLE
Using pushbutton for play mp3 

### ISSUE THREAD

**Issue by atgeek** [earlephilhower/ESP8266Audio#17]
Is it possibile to play a mp3 from a  remote server by using different  pushbutton? Each of them will play different mp3, and if while playing another pushbutton is pressed, stop the current mp3 and start the other.

**Comment by earlephilhower** [comment]
Howdy,

Yes, it is possible but you'll need to write the code to do it.  For now I'm not planning on adding such a complicated example.  If you'd like you can discuss it at the www.esp8266.com forums where I'm @earlephilhower.

Thx,
-EFP3
