### ISSUE TITLE
Cannot play mp3 file bigger then 2~3 MB from sdcard. 

### ISSUE THREAD

**Issue by HTerminal** [earlephilhower/ESP8266Audio#173]
Hi,

I am taking an MP3 file of 128Kbps converted from Audacity (Open source audio converter). The file source is SDcard.
But each time it the code try to play the file it crashes.

What should I do?

I am compiling at 165MHz and V2 higher bandwidth.

**Comment by HTerminal** [comment]
I was doing something stupid. I was following the wav file player and tried to play mp3. We directly need to feed the file name in the player. Not the tag info.

**Comment by imranaalam** [comment]
@HTerminal are you using ESP32? please share the code. what pin you are using for speaker output ?
