### ISSUE TITLE
No dac and no serial.begin sound quality problem. 

### ISSUE THREAD

**Issue by msilenius** [earlephilhower/ESP8266Audio#177]
on my esp8266 nodemcu when I use the library with no dac and a transistor the sound quality lower a lot if i don't use serial.begin() in my squetch before using the library.

the funny thing is calling serial.begin then serial.end before using the sound keep the quality good

**Comment by msilenius** [comment]
solved not sure how.

**Comment by msilenius** [comment]
solved not sure why.

**Comment by imranaalam** [comment]
you are getting sound output on which pin?
