### ISSUE TITLE
MP3 cannot be played completely  with NoDAC way,about one second sound cut

### ISSUE THREAD

**Issue by qianli2017** [earlephilhower/ESP8266Audio#178]
Thanks for your work!
I can hear the good music from NodeMCU(ESP12E) with the ESP8266Audio Lib although with background noisy.

But I found a defect which is the last almost one second sound is cut, the sound is not played completely when it plays a mp3 with NoDAC way by SPIFFS or HTTP stream.

The output message is below:
... ... 
Running for 20247 ms...
Running for 21248 ms...
Running for 22249 ms...
STATUS(buffer) '3' = 'Buffer underflow'
STATUS(buffer) '2' = 'Refilling buffer'
STATUS(buffer) '3' = 'Buffer underflow'
MP3 stop, len==0
MP3 done
MP3 done

I found the "Buffer underflow" and "Refiling buffer" in AudioFileSourceBuffer.cpp file.
I don't know what happened and how it happened. 

Looking forward to your check and resolve the problem. Thanks.

**Comment by earlephilhower** [comment]
Latest commit should fix chopped terminal MP3 packets.
