### ISSUE TITLE
Creating my own acc sample program memory

### ISSUE THREAD

**Issue by jrdvm** [earlephilhower/ESP8266Audio#185]
How can I create an acc program memory like the samle in sampleacc.h of the PlayAACFromPROGMEM sample?

const unsigned char sampleaac[] PROGMEM = {
  0xff, 0xf1, 0x50, 0x80, 0x1c, 0x3f, 0xfc, 0xda, 0x00, 0x4c, 0x61, 0x76,
  0x63, 0x35, 0x32, 0x2e, 0x37, 0x30, 0x2e, 0x30, 0x00, 0x42, 0x78, 0xa9,
  0xb6, 0x89, 0x29, ...

**Comment by earlephilhower** [comment]
`xxd --include` can make header files from binary files under UNIX.  That's what I used for the examples.
