### ISSUE TITLE
"lwIP Variant" for ESP32

### ISSUE THREAD

**Issue by Colobox** [earlephilhower/ESP8266Audio#186]
How can I setup **"lwIP Variant"** in **"v2 Higher Bandwidth"** for **ESP32** board (DOIT ESP32 DEVKIT V1)?
This item is not in the menu "Tools" in ARDUINO IDE, as for ESP8266.
I have a problem's with MP3 files from HTTP. This is just one MP3 file, not a stream. It breaks at the very end.

**Comment by earlephilhower** [comment]
Sorry, that option is only available for the 8266.  The -32 has only the single option.
