### ISSUE TITLE
MIDI Synth

### ISSUE THREAD

**Issue by AlexFundorin** [earlephilhower/ESP8266Audio#190]
Is it possible to use this library with ESP32 as an external midi synthesizer (not midi player) with sf2 support?
With, maybe, some extra effects, like reverb or delay and general CC support (CC 11 - expression, CC 64 - portamento, etc).

**Comment by earlephilhower** [comment]
Howdy,

It may be possible with some work, but it doesn't seem straightforward.  The current MIDI decoder is a mash-up of a MIDI parser with a libtinysoundfont backend running the note generation.  The MIDI parser would need to have some sort of serial parsing and support streaming MIDI as opposed to the on-disk format.

What might be easiest is to use the ported libtinysoundfont itself and start from that.  It can do the note effects and wavetable synthesis in chunks now, so you're free to put your own code on top to drive real-time effects/sounds using MIDI or a simpler format you yourself define.

Good luck,
-EFP3
