### ISSUE TITLE
Convert wifi stream to audio

### ISSUE THREAD

**Issue by dydx-git** [earlephilhower/ESP8266Audio#192]
Hi, I wanted to know if this library will work with what I'm trying to do right now? I'll be passing audio signal to the arduino by using wifi esp8266 and my phone then convert that stream of data into audio and play it on a some speaker.. is that possible with just esp8266, ardino uno and a speaker?

**Comment by earlephilhower** [comment]
Only the 8266 and speaker are needed.  You will need to write code to do it, probably using AudioFileSourceHTTP or something like that to connect to a server, and then have the server send raw WAV or compressed MP3/etc., and pass it thought the decoder and output driver.  See the examples for some streaming sources.
