### ISSUE TITLE
Question : How to delete/recreate AudioOutputI2S object ?

### ISSUE THREAD

**Issue by JPMJPM** [earlephilhower/ESP8266Audio#208]
Hello,

I am using `out = new AudioOutputI2S (1);`

How can I delete the `out` object to do something different with the I2S 1 interface and after recreate it ?.

Regards.

**Comment by lohannaude** [comment]
I am having the same problem, I have tried <code>out->~AudioOutputI2S();</code> as well but my esp32 keeps shutting down

**Comment by thijsdebont** [comment]
delete out;
You van recreate the object again afterwards
