### ISSUE TITLE
Error compiling for board LOLIN(WEMOS) D1 R2 & mini

### ISSUE THREAD

**Issue by Haykke** [earlephilhower/ESP8266Audio#228]
Hi,
I trying to get it to read an mp3 file from a sd card reader and output it onto a speaker, but when I try compiling any kind of example I get this error:

Arduino: 1.8.10 (Windows 10), Board: "LOLIN(WEMOS) D1 R2 & mini, 160 MHz, Flash, Legacy (new can return nullptr), All SSL ciphers (most compatible), 4MB (FS:2MB OTA:~1019KB), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Multiple libraries were found for "SDFS.h"
In file included from C:\Users\haykk\Documents\Arduino\libraries\ESP8266Audio\src\AudioFileSourceSPIRAMBuffer.cpp:23:0:

 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\SDFS
C:\Users\haykk\Documents\Arduino\libraries\ESP8266Audio\src\AudioFileSourceSPIRAMBuffer.h:27:76: fatal error: ESP8266Spiram.h: No such file or directory

Multiple libraries were found for "SPI.h"
 #include <ESP8266Spiram.h> // https://github.com/Gianbacchio/ESP8266_Spiram

 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\SPI
                                                                            ^

Multiple libraries were found for "SdFat.h"
compilation terminated.

 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266SdFat
Multiple libraries were found for "ESP8266HTTPClient.h"
 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266HTTPClient
Multiple libraries were found for "ESP8266WiFi.h"
 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\ESP8266WiFi
Multiple libraries were found for "AudioFileSourceSD.h"
 Used: C:\Users\haykk\Documents\Arduino\libraries\ESP8266Audio
 Not used: C:\Users\haykk\Documents\Arduino\libraries\ESP8266Audio-master
Multiple libraries were found for "SD.h"
 Used: C:\Users\haykk\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.6.2\libraries\SD
 Not used: E:\Tools\Arduino\libraries\SD
exit status 1
Error compiling for board LOLIN(WEMOS) D1 R2 & mini.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by earlephilhower** [comment]
The library required the ESP8266SpiRAM library earlier, as mentioned in the library.json file and README, which is what the error you're showing is (you also seem to have installed the ESP8266/ESP32 incompatible base Arduino SD library, too, but that's another issue).  The current library doesn't depend on this add'l requirement any more, so an update should get you compiling.
