### ISSUE TITLE
DLNA/Upnp support?

### ISSUE THREAD

**Issue by Qbunjo** [earlephilhower/ESP8266Audio#238]
Hi,
I was looking lately for generic ESP32 DLNA renderer. I know there is of course LyraT and it supports DLNA, but maybe it would be nice to provide DLNA support to ESP WROOM along with some I2S DAC?

**Comment by earlephilhower** [comment]
Sorry, I've not seen any working DNLA setup in years.  If you have a PR, I'd be happy to look at it!
