### ISSUE TITLE
Problem with ESP32

### ISSUE THREAD

**Issue by DavidMR91** [earlephilhower/ESP8266Audio#239]
I'm trying to complile the http demo in my ESP32 Dev kit and i'm reciving this error:

In file included from C:\Users\david\Documents\Arduino\libraries\ESP8266Audio-master\src\driver\SinglePinI2SDriver.cpp:34:0:

C:\Users\david\Documents\Arduino\libraries\ESP8266Audio-master\src\driver\SinglePinI2SDriver.h:24:2: error: #error "This driver is ESP8266 specific, only include it on ESP8266"

 #error "This driver is ESP8266 specific, only include it on ESP8266"

  ^

In file included from C:\Users\david\Documents\Arduino\libraries\ESP8266Audio-master\src\driver\SinglePinI2SDriver.cpp:34:0:

C:\Users\david\Documents\Arduino\libraries\ESP8266Audio-master\src\driver\SinglePinI2SDriver.h:28:19: fatal error: osapi.h: No such file or directory

compilation terminated.

exit status 1
Error compilando para la tarjeta ESP32 Dev Module.

**Comment by ikostoski** [comment]
Mea culpa. As a quick fix, please delete the two files in src/driver (SinglePinI2SDriver.*), it should fix compile issue on ESP32... More permanent fix will follow...
