### ISSUE TITLE
Latest version won

### ISSUE THREAD

**Issue by judge2005** [earlephilhower/ESP8266Audio#257]
I get this error compiling with ESP32-arduino v. 1.0.4.
src\libflac\stream_decoder.c:560:9: error: implicit declaration of function 'init_FILE_internal_' [-Werror=implicit-function-declaration]

**Comment by earlephilhower** [comment]
Can you give the latest push a try, @judge2005 ?  I lost my compile prefs and ended up w/o `-Wall` in my compile options on my dev system.

**Comment by judge2005** [comment]
Same error. I note you moved the #endif down to cover a method that calls it, but two other methods call it, including init_file_internal_(...), and if you remove that one, it will still break because other methods call that.

**Comment by earlephilhower** [comment]
Thanks for the PR!  Closing.
