### ISSUE TITLE
ESP32 with 128Mbit internal EPROM

### ISSUE THREAD

**Issue by Orgelpult** [earlephilhower/ESP8266Audio#261]
In case that I am using an ESP32 with more memory (128Mbit is available) - does this have any anvantages? Can I use a better soundfont then - lets say 8MB or so ...???

**Comment by earlephilhower** [comment]
You can use a ~16MByte soundfont, sure, if it fits after the filesystem.  Otherwise, the real ESP32 advantage is that is much faster and has way more RAM than the 8266, so it's easier to get good quality out.
