### ISSUE TITLE
Wait after reading MP3 file for final frames (#263) 

### ISSUE THREAD

**Issue by NikolaiRadke** [earlephilhower/ESP8266Audio#265]
Dear Earle,

the new commit is not running properly in my setting with ESP32. Function isRunning() is always returning TRUE after finishing playing the file.

Removing your changes does fix the issue.

Kind regarts,
Nikolai

**Comment by earlephilhower** [comment]
Could you please attach a small sample MP3 that shows this?  On tests here I don't seem to be hitting the case.  There might be some encoding format/length/etc. differences, so a sample would be very handy.

**Comment by NikolaiRadke** [comment]
Hi!
Sure. It is a simple "Beep". It runs at startup. I removed it and played some other random files.  After some flawlessly running files, it stopped playing again, so i reckon that your are right, it seems to depend on the encoding format/whatever.

After "Beep", isRunning() always returns TRUE.
Sorry for the Zip, GitHub doesn't allow MP3.

[beep.zip](https://github.com/earlephilhower/ESP8266Audio/files/4576907/beep.zip)

**Comment by earlephilhower** [comment]
Got it.  Thanks, @NikolaiRadke.  Let me run it through the hardware this weekend and see if I can figure out a way to make both things work properly.

**Comment by countrysideboy** [comment]
Hi, I found the same problem with ESP8266.

**Comment by countrysideboy** [comment]
@earlephilhower 
I try to modify the code
from
```
  if (finishing && (unused == buffLen - 1)) {
    return MAD_FLOW_STOP;
  }
```
to
```
  if (finishing && (unused <= buffLen - 1)) {
    return MAD_FLOW_STOP;
  }
```
I didn't go into the code logic, but it seems that I can play music continuously now.
