### ISSUE TITLE
Is there a way to redefine which pins are used for the I2C DAC?

### ISSUE THREAD

**Issue by dagnall53** [earlephilhower/ESP8266Audio#27]
The I2C DAC uses Pins "RX,D8, and D4" 
(Ie " RX, 15, and 2" ).
RX--Din
D8--BCLK
D4--LRC
Is there a way to redefine which pins are used? D4 is very useful as it is the blue led on the ESP module...
Many thanks
Dagnall

**Comment by earlephilhower** [comment]
Not on the esp 8266.  You'll need to add your own LED and resistor to another pin if you want control while audio is playing.
