### ISSUE TITLE
Can support ESP8266SdFat？

### ISSUE THREAD

**Issue by jjbboox** [earlephilhower/ESP8266Audio#272]
I want use ESP8266SdFat for long file name support.
Can Esp8266Audio support ESP8266SdFat？

**Comment by earlephilhower** [comment]
Actually, SD.h on the 8266 uses ESP8266SdFat.  So you should already have LFN support.  Are you not seeing it?

You can also make a class for any filesystem with the following snippet, replacing the **BLAH** with the custom FS you need to add:

````
#include "AudioFileSource.h"
#include "AudioFileSourceFS.h"

class AudioFileSourceBLAH : public AudioFileSourceFS
{
  public:
    AudioFileSourceBLAH() : AudioFileSourceFS(BLAH) { };
    AudioFileSourceBLAH(const char *filename) : AudioFileSourceFS(BLAH, filename) {};
    // Others are inherited from base
};
````
