### ISSUE TITLE
Follow redirects #276

### ISSUE THREAD

**Issue by Maigre** [earlephilhower/ESP8266Audio#280]
Hi,
sorry PR #276 fails on ESP32:
AudioFileSourceHTTPStream.cpp:41:8: error: 'class HTTPClient' has no member named 'setFollowRedirects'

.setFollowRedirects is specific to ESP8266HTTPClient.h (ESP8266)
and missing in HTTPClient.h (ESP32)

I don't know if there is an equivalent on ESP32, 
but best would be to add a conditional execution for this line (ESP8266 only)...

Thanks !
Best Regards,

Thomas

**Comment by earlephilhower** [comment]
Try the latest push.  Just a simple `ifndef ESP32` bracketing should have taken care of it.

**Comment by Maigre** [comment]
It does the job.
Thanks !
