### ISSUE TITLE
Can I play online radio by esp32(M5Stack) on Ethernet ?

### ISSUE THREAD

**Issue by boombavn** [earlephilhower/ESP8266Audio#283]
file = new AudioFileSourceICYStream(URL);
  file->RegisterMetadataCB(MDCallback, (void *)"ICY");
  buff = new AudioFileSourceBuffer(file, 8192);
  buff->RegisterStatusCB(StatusCallback, (void *)"buffer");
  out = new AudioOutputI2S(0, 1);
  out->SetOutputModeMono(true);
  mp3 = new AudioGeneratorMP3();
  mp3->RegisterStatusCB(StatusCallback, (void *)"mp3");
  mp3->begin(buff, out);

I tried this code, it work with wifi but not with ethernet. I use M5stack + w5500 and tested ok with some examples code to check connection..... So Can I play online radio by esp32(M5Stack) + w5500 ? and How ? Thank you very much !

**Comment by earlephilhower** [comment]
You could look at rewriting the AudioSourceHTTP() to use an Ethernet client.  I don't have a M5 so you're on your own there, sorry.  If it uses the standard `Client` interface it may be trivial to add, and I'd love to get a PR with it!
