### ISSUE TITLE
SD error compilation. 

### ISSUE THREAD

**Issue by renat2985** [earlephilhower/ESP8266Audio#3]
Please tell me what I do wrong? Thanks for ESP8266Audio!

![2017 09 29-11 38 28](https://user-images.githubusercontent.com/1230815/31007896-cb1d3c9c-a50a-11e7-8a5d-c201bf86ad22.png)

**Comment by earlephilhower** [comment]
Howdy,

Looks like you have a custom SD library file in ~/Arduino/libraries/SD.  That won't work at all with the ESP8266 ide/sdk.  Remove that and let Arduino use the ESP8266 specific SD card libs and I think you'll be OK.

-EFP3

**Comment by renat2985** [comment]
Thanks. Work.
Do you have plans to make a simple example with a web interface where can add new internet radio? :)

**Comment by earlephilhower** [comment]
No plans now, sorry.  I'm always happy to get pull requests, though. :)

**Comment by earlephilhower** [comment]
Closing as this was resolved.
