### ISSUE TITLE
Could we get PTTTL (plyphone TTTL) playback as well?

### ISSUE THREAD

**Issue by beoran** [earlephilhower/ESP8266Audio#307]
PTTTL seems like a great idea for embedded use. I'd love to use it for my T-Watch-2020 :)
https://github.com/eriknyquist/ptttl
Any interest in this?

**Comment by earlephilhower** [comment]
@beoran I'm always happy to get PRs!  For PTTTL it looks like a pretty simple generator.  You can use the existing RTTTL as a start.  Good luck!
