### ISSUE TITLE
Hello!what I should do if I use GSM module to play NETWORK MP3 files For example, SIM800L

### ISSUE THREAD

**Issue by amibk** [earlephilhower/ESP8266Audio#320]
Hello, this library is fantastic! Could you tell me what I should do if I use GSM module to play NETWORK MP3 files? For example, SIM800L, I have checked the relevant documents and found that SIM800L module communicates with AT command. "AudioFileSourceICYStream" in your library USES WIFI for HTTP. Then how should AT command replace WIFI? I am very sorry, I searched a lot of information, but Still have no idea...

**Comment by earlephilhower** [comment]
If you have a GSM modem, you'll need to write your own streaming source.  Pattern it off of the HTTP source.  You'll have to replace the connection setup and reading with the appropriate AT commands over a serial port.  I think it would not be too hard if you can already use the GSM modem to connect to a HTTP server and read a web page. 

Good luck!
