### ISSUE TITLE
how to change BCLK frequency?

### ISSUE THREAD

**Issue by Skbyeon** [earlephilhower/ESP8266Audio#337]
hi, i using example PlayMP3FromSPIFFS 

and I use Class-D Amplifier MAX98357A Series.

this amplifier need to input a BCLK = 3.072MHZ, 
but esp8266, PlayMP3FromSPIFFS example generate BCLK aboue 1.5MHZ.
LRCLK is ok. (48kHz)

how can I?

Thanks

**Comment by jayzakk** [comment]
For 48000Hz, 16 Bit, Stereo , BCLK is 1.536 MHz (48000*16*2).
There is no "need" of an higher BCLK. Why do you think it "needs" 3.072MHz? This would require double the sample rate (96kHz) or double the resolution (32 bits) to be generated by ESP8266Audio.

**Comment by earlephilhower** [comment]
Thanks @jayzakk
