### ISSUE TITLE
midi callbacks

### ISSUE THREAD

**Issue by fkoteam** [earlephilhower/ESP8266Audio#352]
Hello,
I think it's not possible yet, but it would be great if this library could have callbacks in each note on/off on midi playback. The callbacks could be used to control leds, for example.
 
I looked the code but my knowledge is limited.

Thank you! ;)

**Comment by earlephilhower** [comment]
Look at https://github.com/earlephilhower/ESP8266Audio/blob/master/src/AudioGeneratorMIDI.cpp.  There are obvious spots where notes are started and ended that you can hack into.  Good luck!
