### ISSUE TITLE
HTTPC_FORCE_FOLLOW_REDIRECTS not declared

### ISSUE THREAD

**Issue by DanDor90** [earlephilhower/ESP8266Audio#362]
Board: Wemos D1 mini (ESP8266)

When running any http-related examples with 

`const char *URL="http://br-b5aktuell-live.cast.addradio.de/br/b5aktuell/live/mp3/low"`

I get the following error:

```
\Arduino\libraries\ESP8266Audio-master\src\AudioFileSourceHTTPStream.cpp: In member function 'virtual bool AudioFileSourceHTTPStream::open(const char*)':

\Arduino\libraries\ESP8266Audio-master\src\AudioFileSourceHTTPStream.cpp:43:27: error: 'HTTPC_FORCE_FOLLOW_REDIRECTS' was not declared in this scope

http.setFollowRedirects(HTTPC_FORCE_FOLLOW_REDIRECTS);
```

Am I missing any particular library?

**Comment by d-a-v** [comment]
Did you try to update your esp8266/arduino core to the 2.7.4 version ?

**Comment by DanDor90** [comment]
Thanks a lot, that fixed the problem. I was running an older version of the esp8266 core on the Arduino IDE. Upgrading to 2.4.7. solved the problem and I was able to compile.

**Comment by xitonghan** [comment]
updata is ok!
thx
