### ISSUE TITLE
esp32 no output when use_apll = 1

### ISSUE THREAD

**Issue by h3ndrik** [earlephilhower/ESP8266Audio#37]
I have two esp32 development boards. One works fine with use_apll=1, the other one does not output anything with the same code. only when i set use_apll=0
both claim to be revision 1

**Comment by earlephilhower** [comment]
Does the auto-detection you added fix this?

**Comment by h3ndrik** [comment]
unfortunately not. i think this board might have a different XTAL frequency, or some other crystal. but i still don't know what's funny about that board. disabling apll helps for now.
this might not be a bug of ESP8266Audio at all.
