### ISSUE TITLE
Moving to libmpg123

### ISSUE THREAD

**Issue by yoav-klein** [earlephilhower/ESP8266Audio#393]
I was just curious why using `libmad` rather than `libmpg123`?

**Comment by earlephilhower** [comment]
Memory usage was my concern.  On the ESP8266 we have ~45KB total free RAM to work with, so things are very tight for MP3 or AAC decode.

There's also the RealPlayer MP3 codec (MP3A) also included in the library already, FWIW.  It uses too much memory to even run on the 8266, though, so it's not used in any examples.
