### ISSUE TITLE
Web interface

### ISSUE THREAD

**Issue by renat2985** [earlephilhower/ESP8266Audio#4]
I'm trying to implement a web interface with my friend. But your library refuses to work correctly. We will be very happy if you can help me.

https://github.com/tretyakovsa/ESP_WIFI_RADIO

https://github.com/tretyakovsa/ESP_WIFI_RADIO/blob/master/ESP_WIFI_RADIO.ino#L43-L44
```ino
void loop() {
  //handleAudio();
}
```

https://github.com/tretyakovsa/ESP_WIFI_RADIO/blob/master/Audio.ino#L11-L16

```ino
  if (mp3->isRunning()) {
    if (!mp3->loop()) mp3->stop();
  } else {
    Serial.printf("MP3 done\n");
    delay(1000);
}
```

![2017 10 01-01 08 52](https://user-images.githubusercontent.com/1230815/31049845-23a8e63c-a645-11e7-8b1d-18c708eb3dc0.png)

**Comment by earlephilhower** [comment]
What exactly is the problem?  Basically you set it up with the httpsreader then in your main loop() you need to pump the mp3->loop() call one or more times to have it generate samples for the audio output.

**Comment by earlephilhower** [comment]
Also, just for sanity, have you been able to run one of the simple PROGMEM examples like PlayWAVFromPROGMEM and hear it?  If not, there's some HW issue and you'll need to check your wiring...

**Comment by earlephilhower** [comment]
Closing this as I think you're consolidating everything in bug #13.
