### ISSUE TITLE
I2s to lossless file 

### ISSUE THREAD

**Issue by artouste** [earlephilhower/ESP8266Audio#411]
Hello

I discovered with your work on the PICO2040 and your esp pico I2s audio lib
I progress at my own pace by working with this adc
https://www.audiophonics.fr/fr/appareil-hifi-adc-audio/module-adc-stereo-wm8782-i2s-24bit-192khz-p-14897.html

I did not find (poorly read?) An example allowing to acquire I2S and to save it on sd card
with a lossless format.
anyway, thank you for your work on pico and audio

P artouste

**Comment by earlephilhower** [comment]
This library's not needed or useful for your app.  Simply use the Arduino core's I2S_read() function and write the returned data to a File.  There aren't any examples I know of, but it is very simple to just store the raw data.  You could theoretically write a WAV header (many online refs for this) in the file to make it a valid WAV source, but even raw bits can be used by most audio apps.

Good luck!
