### ISSUE TITLE
I2S ADC on esp8266 esp32 PICO2040

### ISSUE THREAD

**Issue by artouste** [earlephilhower/ESP8266Audio#415]
Hello
Still in my I2S acquisition learning phase
I just saw with my tests that there is no common basis for the esp8266 esp32 and pico2040, to do a simple acquisition on the 3 target MCUs.

In a previous issue
https://github.com/earlephilhower/ESP8266Audio/issues/411
you would advise:

 Simply use the Arduino core's I2S_read () function and write the returned data to a File. There aren't any examples

Under arduino IDE I have to use i2s.h with the esp32 or esp8266 package, but a priori the functions are not all the same

So far I have more or less managed to get by for the esp32, I also saw on this occasion that the esp32 does not support more than 150 kHz in acquisition.

for esp8266 an example "transmit to udp" seems functional (micro I2S at 11025 16bits)
for the pico2040 ... i will look later.

If you could guide me in regards to I2S acquisition on these 3 target MCUs that would be nice, I'm a bit lost

Thank you
phil

**Comment by earlephilhower** [comment]
I think you have the picture already.  There will be some I2S setup calls to adjust frequency, bitrate, etc, and then it's just i2s_read (or whatever the specific MCU call is) followed by writing the same data you just read.  You can also look at the Arduino `I2S` class (included on the ESP8266 and RP2040 cores, not sure about ESP32) which should give about the same API across different boards.

Note that for the RP2040, in my Arduino core ( https://github.com/earlephilhower/arduino-pico ) that I2S reading is not supported.  I use the Pico SDK Extras to implement I2S using the PIO machine, and there they do not include a I2S input emulation.  You can check the Arduino.cc MBED version (available through the Boards Manager in the IDE) to see if it supports I2S.  (My quick scan says not, but I could very well be wrong!)  You could also look at Circuit Python for the RP2040 which I do believe implements an I2S input emulator.

Good luck!
