### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by medvosa** [earlephilhower/ESP8266Audio#423]
Hello. Oned more question.

Is there any possibility of implementing equalizer functionality using your library, for example I want to make bass a bit louder?
I found mixer example but as I understood it supports only SetGain function that is used for velume adjustmnent, am I right?

p.s. I solved my problem with DAC. thanks.

**Comment by earlephilhower** [comment]
There is no way now to do a frequency-based equalizer.  In general we don't have frequency-domain data available to adjust gain on separate bands.  For the MP3, there is a hook we don't presently use in the LIBMAD that allows you to see the frequency domain of each chunk, but you'll be on your own to handle that.

Alternatively, if you implement a series of FIRs, it is possible to filter the time-domain output of the decoder to add gain using a series of band-pass filters.  I'm not sure that's a reasonable thing to do, however.

Good luck!
