### ISSUE TITLE
AudioFileSourcePROGMEM ... accept const unsigned char only  

### ISSUE THREAD

**Issue by ahmednaser89** [earlephilhower/ESP8266Audio#429]
thanks allot ...great lib 
AudioFileSourcePROGMEM ... accept const unsigned char only  
I want to set the data of progmem file source
any solution

**Comment by earlephilhower** [comment]
You can just pass in a memory array from the heap, it will treat it as a const even if it isn't:
````
....
char *data = (char*)malloc(8192);
// Set up the data[] elements in your own code
auto pmem = new AudioFileSourcePROGMEM (data, 8192);
...
````
