### ISSUE TITLE
Examples don't compile

### ISSUE THREAD

**Issue by marcboon** [earlephilhower/ESP8266Audio#434]
Arduino 1.8.16
esp8266 3.0.2

I can't get any of the examples to compile. Tried different board setting (Wemos D1 mini, AdaFruit Feather ESP8266), but that doesn't make a difference. I'm getting tons of error messages, mostly about SD and SdFat. It seems that conflicting versions of these libraries are being mixed. The last messages are:
```
Multiple libraries were found for "SD.h"
 Used: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\SD
 Not used: C:\Program Files (x86)\Arduino\libraries\SD
Multiple libraries were found for "SdFat.h"
 Used: D:\Documents\Arduino\libraries\SdFat
 Not used: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266SdFat
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266WiFi 
Using library ESP8266Audio-master at version 1.9.3 in folder: D:\Documents\Arduino\libraries\ESP8266Audio-master 
Using library ESP8266HTTPClient at version 1.2 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\ESP8266HTTPClient 
Using library SD at version 2.0.0 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\SD 
Using library SDFS at version 0.1.0 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\SDFS 
Using library SPI at version 1.0 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\SPI 
Using library SdFat at version 2.1.0 in folder: D:\Documents\Arduino\libraries\SdFat 
Using library I2S at version 1.0 in folder: C:\Users\marc\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.0.2\libraries\I2S 
```
I get these messages also for examples that don't use SD/SdFat at all. The Arduino builder seems a little over-ambitious in compiling everything in the library, including files that are not even referenced in the sketch, for example PlayWAVFromPROGMEM.ino

**Comment by squio** [comment]
Same here, same versions but on Mac OS:

- Arduino 1.8.16
- esp8266 3.0.2

Trying to compile the WebRadio example

**Comment by squio** [comment]
OK solved it:

I had two SD related libraries in the same folder where the ESP8266Audio is installed (NOT the `Arduino15` library path, the setup still confuses me):

- SD
- SdFat

Just deleting both of these works for me

**Comment by earlephilhower** [comment]
Yes, having Arduino generic SD and SDFAT will cause this (and most other things which need them!) to fail to build;.  Only install the ESP specific versions.
