### ISSUE TITLE
Bad naming choice in AudioGeneratorMOD ligne 59

### ISSUE THREAD

**Issue by vcchm** [earlephilhower/ESP8266Audio#449]
I took me quite a time to find why a code running on M5Stack did not work with M5Atom ! Which is a pity because M5Atom offers a great mix for building a MOD player (https://shop.m5stack.com/products/atom-speaker-kit-ns4168) - SD Card+Esp32+Button+ampliicator+Mini speaker+Jack connectivity
 
The problem is that the "DIVIDER" macro in AudioGeneratorMOD.h ligne 59 
    enum {DIVIDER = 10};    

conflicts with M5ATOM's "DIVIDER" parameter in FastLED\src/platforms/esp/32/clockless_rmt_esp32.h line 150
#define DIVIDER 2

Suggestion : name it MOD_DIVIDER instead of DIVIDER in next versions in both AudioGeneratorMOD.h and AudioGeneratorMOD.cpp

**Comment by earlephilhower** [comment]
:)  One might say that FastLED and ESP826Audio *both* made a poor choice in naming.

The name there came the original upstream sources.  A simple namespacing could also avoid the issue, but a search/replace would be fine, too.  Would you like to make a PR?

**Comment by vcchm** [comment]
Indeed - two bad choices !  I tried to do a PR, but not sure I did it the right way...

By the way congrats for the code, really nice. I just sometimes have problems with some mods such as these which do not work..

[Ackerlight1.zip](https://github.com/earlephilhower/ESP8266Audio/files/7612495/Ackerlight1.zip)
