### ISSUE TITLE
Free Heap memory is full

### ISSUE THREAD

**Issue by linh-danh-thue-KN** [earlephilhower/ESP8266Audio#485]
![image](https://user-images.githubusercontent.com/97775916/149609963-ee172253-104c-4f6e-a622-b19d7075de72.png)

**Comment by earlephilhower** [comment]
Without somet

**Comment by Martin-Laclaustra** [comment]
@linh-danh-thue-KN @earlephilhower 
I think that I remember finding that there is a small memory leak related to the string that defines the file to play. I can not give a lot of detail right now, but I think that completely deleting the FileSource object and recreating it each time solved the leak.
Earle, please tell me if you would be interested in more detail about this and I could try to rescue my old code in which I tested it.
