### ISSUE TITLE
Does this work for playing audio files from the file system by AudioFileSourceBuffer？

### ISSUE THREAD

**Issue by yihua-wang** [earlephilhower/ESP8266Audio#487]

**Comment by yihua-wang** [comment]
Play audio files from the SD file system using a buffer to avoid frequent manipulation of the file system

**Comment by earlephilhower** [comment]
There is a buffered input class you can try https://github.com/earlephilhower/ESP8266Audio/blob/master/src/AudioFileSourceBuffer.h.  Pass in the AudioFileSource, and use its output to the AuidioGenerator.  Under steady-state, though, I'm not sure it really will impact the amount of FS manipulations required.
