### ISSUE TITLE
Is AudioOutputSPDIF usable to convert I2S to SPDIF

### ISSUE THREAD

**Issue by MichaelBuechel** [earlephilhower/ESP8266Audio#494]
Hi all,
I am trying to find a I2S to SPDIF SW converter for  [ESP32-Radio 2.0](https://github.com/Edzelf/ESP32Radio-V2)](https://github.com/Edzelf/ESP32Radio-V2). 

The Idea is to hook AudioOutputSPDIF  up to the exiting I2S Outputs Pins in parallel, to the I2S Out signals.
So can I do so ? i.e declare these EPS32 output pins using  SetPinout(int bclkPin, int wclkPin, int doutPin)
and let the class decode in parallel ?

Regard Michael

**Comment by earlephilhower** [comment]
The class encodes, not decodes.  What I'd do is hack into the ESP32radio "write to i2s" and have it either write to both the existing I2S and to the SPDIF output object, or just to the SPDIF output object if you don't need I2S at all.
