### ISSUE TITLE
WCLK pin used on RP2040 build.

### ISSUE THREAD

**Issue by stolk** [earlephilhower/ESP8266Audio#507]
I am confused by the different `AudioOutputI2S` definitions for _ESP32_ and _RP2040_.

For the _ESP32_, the **WCLK**, **BCLK**, **DOUT** pin can all be set.

For the _RP2040_, only the **BCLK** and **DOUT** pins are set.

How do I specify which GPIO will be used for **WCLK**(aka as WSEL or FS?)

```
AudioOutputI2S::AudioOutputI2S(long sampleRate, pin_size_t sck, pin_size_t data) {
    i2sOn = false;
    mono = false;
    bps = 16;
    channels = 2;
    hertz = sampleRate;
    bclkPin = sck;
    doutPin = data;
    SetGain(1.0);
}
```

**Comment by earlephilhower** [comment]
You cannot define a WCLK on the RP2040 as a limitation of the PIO.  It's always GPIO # SCK+1
