### ISSUE TITLE
Incorrect parameter check in AudioOutputI2SNoDAC::SetOversampling

### ISSUE THREAD

**Issue by phoddie** [earlephilhower/ESP8266Audio#55]
In `AudioOutputI2SNoDAC::SetOversampling`, the oversampling value is parameter checked against 256:
https://github.com/earlephilhower/ESP8266Audio/blob/0bb859037b39dd022e407442545712feb24044ac/src/AudioOutputI2SNoDAC.cpp#L43

The text on the repository's `readme` states: 
> software delta-sigma DAC with 32x oversampling (up to 128x if the audio rate is low enough)

The implementation of `AudioOutputI2SNoDAC::ConsumeSample` passes a `dsBuff` of 4 32- bit values, for a total of 128 bits, to `AudioOutputI2SNoDAC::DeltaSigma` which determines the number of 32-bit values to output by dividing the oversampling value by 32:
https://github.com/earlephilhower/ESP8266Audio/blob/0bb859037b39dd022e407442545712feb24044ac/src/AudioOutputI2SNoDAC.cpp#L56

If the oversampling is set higher than 128, it appears `AudioOutputI2SNoDAC::DeltaSigma` will write more than 4 32-bit values, overflowing `dsBuff`.

Apologies if my analysis is incorrect, as I'm not yet set-up to run the code.

**Comment by earlephilhower** [comment]
Very good eyes!  Just pushed the simple fix.  256x oversampling normally runs into I2S max-frequency issues anyway.
