### ISSUE TITLE
Something is not alright with hardware serial

### ISSUE THREAD

**Issue by eporocrail** [earlephilhower/ESP8266Audio#56]
I am trying to get your software running but at the first compiling effort I get the message:
'class HardwareSerial' has no member named 'printf_P'
   if (!buffer) Serial.printf_P(PSTR("Unable to allocate AudioFileSourceBuffer::buffer[]\n"));

How do I proceed

Regards
Ellard

**Comment by earlephilhower** [comment]
Please use the latest 2.4.0 or GIT head version of the IDE.  It was released a little over a month ago and includes these new functions.  I think the Arduino IDE itself can help you upgrade, just go to the boards manager.
