### ISSUE TITLE
Missing library for RPi Pico W

### ISSUE THREAD

**Issue by AgreeDK** [earlephilhower/ESP8266Audio#563]
I have been using your great lib on different esp32 boards and it works fine, now Im trying to use it on the new Raspberry Pi Pico W, but I can't make it work , it can't compile / find 'AudioSourceHTTPStream' which normal use 'HTTPClient.h' for esp32, but I have not been able to find any http client for Rpi Pico W.

Please let me know if Im missing something ?
Thx in advance for your help.

**Comment by earlephilhower** [comment]
Sorry, there is only one of me and many demands on my time.  There is no included HTTPClient library yet for the RP2040 core.  If you'd like to port the ESP8266 version, that would be awesome, but otherwise you'll have to wait until I get OTA and a few other things written and  merged there.
