### ISSUE TITLE
Pins for I2S DAC chip

### ISSUE THREAD

**Issue by renegadeandy** [earlephilhower/ESP8266Audio#58]
Hi all,

Having had marginal success with the NoDAC options I opted to buy one of these:

https://www.aliexpress.com/item/1PCS-PCM5102-PCM5102A-DAC-decoder-I2S-raspberry-red-core-player/32818888303.html

I need assistance wiring the pins up correctly. I am using the ESP8266 ESP-12-E, see its pins here:

https://i.pinimg.com/564x/0c/8c/e8/0c8ce8bc22ee6ba0e2ed830bcbb28454--diy-electronics-arduino.jpg

If i want to run the AACExample in the examples dir, what do I wire the LRCK,DATA and BLK pins to on the ESP?

VCC : 5v
GND : 5v gnd
GND : 5v gnd
LRCK : ???
DATA   ;???
BLK ; ???

**Comment by earlephilhower** [comment]
Check out http://www.esp8266.com/wiki/lib/exe/fetch.php?media=pin_functions.png
