### ISSUE TITLE
Does the AudioFileSourceHTTPStream works with HTTPS ?

### ISSUE THREAD

**Issue by yoav-klein** [earlephilhower/ESP8266Audio#595]
I was using this library for playing radio from an ESP8266 with much pleasure for about over a year, and it was
working fine. Suddenly it stopped working. When debugging, I noticed that the URL I was using
was changed to `https://whatever`. So my question is: does the `AudioFileSourceHTTPStream` class
should work with HTTPS sources?

**Comment by earlephilhower** [comment]
On the 8266 there isn't enough RAM to do Https and Mp3 at the same time. Probably not enough CPU, too.

On the ESP32 or Rpi Pico it might work but you'll need to make aHTTPS class.

**Comment by yoav-klein** [comment]
Are there any instructions on how to use this library with the RPI Pico?
