### ISSUE TITLE
Stream on SHOUTcast D.N.A.S. 

### ISSUE THREAD

**Issue by renat2985** [earlephilhower/ESP8266Audio#6]
http://lr4mp1.latvijasradio.lv:8020/
From this url SHOUTcast can stream mp3: http://lr4mp1.latvijasradio.lv:8020/;stream.mp3

I'm use this example https://github.com/earlephilhower/ESP8266Audio/blob/master/examples/StreamMP3FromHTTP/StreamMP3FromHTTP.ino
```
// Randomly picked URL
const char *URL="http://lr4mp1.latvijasradio.lv:8020/;stream.mp3";

```

But it does not work. Tell me why? Thanks.

**Comment by earlephilhower** [comment]
The URL says ".mp3" but the actual; encoded format is AAC, which is not supported and a different codec:

earle@server:/tmp$ mplayer "http://lr4mp1.latvijasradio.lv:8020/;stream.mp3"
MPlayer 1.2.1 (Debian), built with gcc-5.3.1 (C) 2000-2016 MPlayer Team
mplayer: could not connect to socket
mplayer: No such file or directory
Failed to open LIRC support. You will not be able to use your remote control.

Playing http://lr4mp1.latvijasradio.lv:8020/;stream.mp3.
Resolving lr4mp1.latvijasradio.lv for AF_INET6...

Couldn't resolve name for AF_INET6: lr4mp1.latvijasradio.lv
Resolving lr4mp1.latvijasradio.lv for AF_INET...
Connecting to server lr4mp1.latvijasradio.lv[159.148.56.131]: 8020...

Name   : Radio 4
Genre  : 
Website: http://lr4.latvijasradio.lv
Public : no
Bitrate: 48kbit/s
Cache size set to 320 KBytes
Cache fill:  0.00% (0 bytes)   
ICY Info: StreamTitle='';StreamUrl='http://lr4.latvijasradio.lv';
Cache fill: 15.00% (49152 bytes)   

**AAC file format detected.**
==========================================================================
Opening audio decoder: [ffmpeg] FFmpeg/libavcodec audio decoders
libavcodec version 56.60.100 (external)
AUDIO: 44100 Hz, 2 ch, floatle, 0.0 kbit/0.00% (ratio: 0->352800)
**Selected audio codec: [ffaac] afm: ffmpeg (FFmpeg AAC (MPEG-2/MPEG-4 Audio))**
==========================================================================
AO: [pulse] 44100Hz 2ch floatle (4 bytes per sample)
Video: no video
Starting playback...
A:   1.5 (01.4) of 0.0 (unknown)  0.4% 36% 


MPlayer interrupted by signal 2 in module: play_audio


MPlayer interrupted by signal 2 in module: enable_cache
A:   1.5 (01.5) of 0.0 (unknown)  0.4% 36% 

Exiting... (Quit)
earle@server:/tmp$
