### ISSUE TITLE
AudioOutputI2S(0, 1)   vs   AudioOutputI2SNoDAC

### ISSUE THREAD

**Issue by CobaltEcho** [earlephilhower/ESP8266Audio#647]
What's the difference between using:
`AudioOutputI2SNoDAC.h  //Abuses the I2S interface to play music without a DAC`
vs
`out = new AudioOutputI2S(0, 1);  // use the internal DAC channel 1 (pin25) on ESP32`

I'm trying to play a WAV file from an SD Card Reader.  I would like to get a line level output so I can connect it to a larger (TPA3118) amp.

**Comment by positron96** [comment]
I'd say that you need a true DAC option (2nd). NoDAC is sort-of PWM, so an external amplifier might not like that.
