### ISSUE TITLE
 SetGain(float 0.0 ... 4.0)?

### ISSUE THREAD

**Issue by Mir1001** [earlephilhower/ESP8266Audio#701]
In all examples, we see SetGain in rage from 0.0 to 1.0. But in the code, we have a commit:

> A new SetGain(float 0.0 ... 4.0) method can scale the output volume of an I2S DAC or SW DAC by scaling the samples. Proper clipping is performed.

Which is the correct range? In both cases, we need clarification (fix code range) or the note in documentation.

Thanks

**Comment by earlephilhower** [comment]
Err, gain of 1.0 means "output === input".  Gain of 2.0 means "output  == 2 * input" (i.e. overdrive and expect clipping on a good source), etc.
