### ISSUE TITLE
Why are there so may PRs open, is this project abandoned?

### ISSUE THREAD

**Issue by bsvdoom** [earlephilhower/ESP8266Audio#712]
I see 25 Pull requests open, many stalls for years, without any response, is this project dead, or why is there no attention towards those PRs?

**Comment by earlephilhower** [comment]
Not abandoned, just backlogged. 25 open PRs is nothing...you should have seen the ESP8266 and ESP32 Arduino core before the great purge and auto-close!

Many of the PRs are related to ESP IDF changes.  Every release they seem to redo the I2S API in a subtly incompatible way to the prior version, so a good portion of ones aren't currently relevant.  They should probably be scrubbed looking only at the latest IDF (5.1?) and Arduino-ESP32 (3.x).  Some PRs also only work for some person's very specific use case or environment, so aren't really good candidates for merge.
