### ISSUE TITLE
i2s and ESP8266WiFi cause reset at Wemos D1

### ISSUE THREAD

**Issue by jivido** [earlephilhower/ESP8266Audio#73]
Hi! 
I found out that running this piece of code may result in crashes and reboots
`#include <Arduino.h>
#include "AudioOutputI2S.h"
#include <ESP8266WiFi.h>

AudioOutputI2S *out;

void setup() {
  Serial.begin(115200);
  out = new AudioOutputI2S();
  WiFi.mode(WIFI_AP);
  Serial.println("End of setup()");  
}

void loop() {

}`

The use of the WiFi class after initializing i2s with AudioOutputI2S() causes strange behaviour. 
The module resets _ets Jan 8 2013,rst cause:2, boot mode:(3,6)_ sometimes, especially in programs with more code and more pins used (I use the Wemos SD shield (D1, D5, D6, D7)  and the Wemos WS2812b (D2) shield). I use a PCM5102 i2s DAC (RX0, D4, D8) btw. I power the module with usb, connected to a 500mA 5V port. 
'Cause: 2' seems to indicate that it's something with the reset-pins. Since i2s outputs its clock signal over D8 it might have something to do with it?
Calling _i2s_end()_ before I make calls to WiFi solves the problem.

Maybe running i2s and using WiFi-functions takes too much power which causes a reset?
Not sure if this is an issue with the lib, or simply something one must not do... Maybe someone with the same problem might find this useful.

**Comment by earlephilhower** [comment]
You need a better power supply as you mentioned.  The streaming examples all are running WiFi, obviously, and doing compute/decode of MP3 or AAC and I2S output.  

You should try a different USB port on your PC, too.  The direct-connect motherboard ones are often higher current than the ones added to, say, internal memory card readers.

**Comment by earlephilhower** [comment]
Closing as a HW issue.  Hope you can find a good PS!  It's surprisingly hard to find a good one (I've heard legit Apple branded USB chargers are quite good, if Tom's Hardware teardowns are to be believed).

**Comment by jivido** [comment]
Thanks! I will let you know what happens (probably everything will be fine :))
