### ISSUE TITLE
Only a question for an idea

### ISSUE THREAD

**Issue by ErichHeinemann** [earlephilhower/ESP8266Audio#78]
Hi Earle, 
I am still playing around with Your libraries.
Do You have any idea how to stop a WAV while it is playing? I use files from SD or PROGMEM. 
I use them in the loop-section of the Ardiono-Sketch and around checking the Sound and Starting new sounds I check some sensors or buttons to know when to start a new AudioFile.
After triggering a Audio-WAV it seems that I have to wait till it is played. .. .or it stopped running to trigger a new one.
It seems that the loops or while-do in the AudioGeneratorWAV takes a longer time and my way to trigger a new WAV does not take any effect.

Any idea how to fix that? Should I check my sensors inside the AudioGeneratorWAV-Class?

What would be a good way to stop a WAV even it was not played till the end? wav->stop? .. delete file etc?

Sometimes I use a Button or a Piezo to trigger a WAV, it is not only a simple Line of Code. How could I integrate this with the Class to get a good responsive for good triggering?

Best Regards
Erich

**Comment by earlephilhower** [comment]
It *should* stop as soon as it loads the I2S buffers.  Are you seeing it running to completion on the first wav->loop() call?  If so, that's probably a bug.

To stop, just delete the AudioGeneratorWAV and AudioFileSourceSPIFFS objecst and make new ones.
