### ISSUE TITLE
Compatibility issue with Mesh library

### ISSUE THREAD

**Issue by rkoptev** [earlephilhower/ESP8266Audio#87]
Hi again,

I'm having problems working with this library together with painlessMesh library: https://gitlab.com/painlessMesh/painlessMesh

With this library I receive no sound and no errors from ESP8266Audio. It looks like i2s interface is starting, the clock signals are working normally. However, the data line is empty. Does the library use any global resources, such as timers or interrupts, that can conflict with other libraries?

And if so, can it be fixed on ESP?

Thank you in advance,

Ruslan

**Comment by earlephilhower** [comment]
Howdy,

The ESP8266Audio libs don't use HW resources other than the I2S hardware.  Make sure you're calling the wav->loop() method frequently in your loop(), that there's no busy-waiting in the lib you're trying to use (if it's busy-waiting, add in calls to the audio->loop() method or else the I2S will underflow), etc.

Also, obviously, make sure that you've got enough free RAM to handle whatever you're doing.  The MP3 lib eats a ton of memory, so you may want to start with the RTTTL libs which use next to none, just to verify your chain.

Good luck
-EFP3

**Comment by rkoptev** [comment]
Thank you for the explanation, @earlephilhower,
Looks like the issue was really in free memory. I have only 20 kilobytes of free heap, and seems, it' not enough for MP3. The RTTTL works fine. So I replaced MP3 with WAV and all is working now. Of course, I had to lose compression, but I think I'll fit in 3MB without problems)
