### ISSUE TITLE
SPIFF namespace issue

### ISSUE THREAD

**Issue by HumamHelfawi** [earlephilhower/ESP8266Audio#93]
Hi 
In AudioFileSourceSPIFFS.h, at line 46:

`File f;`

It would be better if it was:

`fs::File f;`

So no conflict with other library that define `FS_NO_GLOBALS`. I tired to make `Hotfix` but I do not have permission (I think I am doing it wrong since I am so dump in using Git)

Thanks!

**Comment by earlephilhower** [comment]
Thanks for the note.  To do a pull request you'd first fork the repo to your own group via the web page button, check that out, change, test, and build on your system, commit and push those changes back to your own repo, and then finally use the web interface to generate a pull request.

It's simpler than it looks from the above description, believe me. :)

Anyway, I've added your change and done a few builds and all seems fine.  The whole Arduino File class system (SD/SPIFFS) is a mess.  Ugh!
