### ISSUE TITLE
how to connect a i2s dac to the wemos d1 mini?

### ISSUE THREAD

**Issue by Primus007** [earlephilhower/ESP8266Audio#98]
i can not figure out the correct pins to connect a pcm5102 dac to my wemos.
my dac has: LCK, DIN, BCK
to which pins must i connect these on the wemos?

This is my dac: http://masterandrey.com/images/Sound-Card-I2S-PCM5102.jpg

Thank you for help.

**Comment by kosso** [comment]
@Primus007 Could you possibly share the solution? Thanks. 

I have the same board and Google brought me here while looking for the connections ;)

**Comment by Primus007** [comment]
![wemos_dac](https://user-images.githubusercontent.com/6861874/40914108-3433d6fa-67f7-11e8-8742-c67a9882451f.JPG)

The 5v power comes from the usb connection on the wemos. in my case it works fine.

**Comment by kosso** [comment]
@Primus007  Perfect. Thanks! 👍
